@echo on

set PACLI="C:\PACLI\PACLI.EXE"
	
call %PACLI% INIT
call %PACLI% DEFINEFROMFILE PARMFILE=Vault.ini
call %PACLI% DEFAULT VAULT="Vault" USER=administrator
call %PACLI% LOGON LOGONFILE=pacli.cred 



FOR /F %%i IN (safelist.txt) DO call %PACLI% OPENSAFE SAFE=%%i

FOR /F %%i IN (safelist.txt) DO call %PACLI%  ADDOWNER OWNER=epvuser1 SAFE=%%i RETRIEVE=NO STORE=NO DELETE=NO ADMINISTER=NO SUPERVISE=NO BACKUP=NO MANAGEOWNERS=NO ACCESSNOCONFIRMATION=NO VALIDATESAFECONTENT=NO LIST=YES USEPASSWORD=YES



call %PACLI% LOGOFF VAULT="Vault" USER=administrator

call %PACLI% TERM