@echo on

set PACLI="C:\PACLI\PACLI.EXE"
	
call %PACLI% INIT
call %PACLI% DEFINEFROMFILE PARMFILE=Vault.ini
call %PACLI% DEFAULT VAULT="Vault" USER=administrator
call %PACLI% LOGON LOGONFILE=pacli.cred 



FOR /F %%i IN (safelist.txt) DO call %PACLI% ADDSAFE SAFE=%%i SAFEOPTIONS=704
FOR /F %%i IN (safelist.txt) DO call %PACLI% ADDSAFESHARE SAFE=%%i GWACCOUNT="PVWAGWAccounts" 
FOR /F %%i IN (safelist.txt) DO call %PACLI% OPENSAFE SAFE=%%i
FOR /F %%i IN (safelist.txt) DO call %PACLI% ADDOWNER OWNER=PasswordManager SAFE=%%i RETRIEVE=YES STORE=YES DELETE=YES ADMINISTER=NO SUPERVISE=NO BACKUP=NO MANAGEOWNERS=NO ACCESSNOCONFIRMATION=YES VALIDATESAFECONTENT=NO LIST=YES USEPASSWORD=YES UPDATEOBJECTPROPERTIES=YES INITIATECPMCHANGE=YES INITIATECPMCHANGEWITHMANUALPASSWORD=YES CREATEFOLDER=YES DELETEFOLDER=YES MOVEFROM=YES MOVEINTO=YES VIEWAUDIT=YES VIEWPERMISSIONS=YES EVENTSLIST=YES ADDEVENTS=YES CREATEOBJECT=YES UNLOCKOBJECT=NO RENAMEOBJECT=YES
FOR /F %%i IN (safelist.txt) DO call %PACLI% ADDOWNER OWNER=myowner SAFE=%%i RETRIEVE=YES STORE=YES DELETE=YES ADMINISTER=YES SUPERVISE=YES BACKUP=YES MANAGEOWNERS=YES ACCESSNOCONFIRMATION=YES VALIDATESAFECONTENT=YES LIST=YES USEPASSWORD=YES UPDATEOBJECTPROPERTIES=YES INITIATECPMCHANGE=YES INITIATECPMCHANGEWITHMANUALPASSWORD=YES CREATEFOLDER=YES DELETEFOLDER=YES MOVEFROM=YES MOVEINTO=YES VIEWAUDIT=YES VIEWPERMISSIONS=YES EVENTSLIST=YES ADDEVENTS=YES CREATEOBJECT=YES UNLOCKOBJECT=YES RENAMEOBJECT=YES


call %PACLI% LOGOFF VAULT="Vault" USER=administrator

call %PACLI% TERM