@echo on

set PACLI="C:\PACLI\PACLI.EXE"
	
call %PACLI% INIT
call %PACLI% DEFINEFROMFILE PARMFILE=Vault.ini
call %PACLI% DEFAULT VAULT="Vault" USER=administrator
call %PACLI% LOGON LOGONFILE=pacli.cred 



FOR /F %%i IN (safelist.txt) DO call %PACLI% OPENSAFE SAFE=%%i



FOR /F %%i IN (safelist.txt) DO call %PACLI% SAFEDETAILS SAFE=%%i SESSIONID={__|sessionid} output(ALL ,ENCLOSE ,RAW ,OEM
,DESCRIPTION ,DELAY ,RETENTION ,OBJECTSRETENTION ,MAXSIZE
,CURRSIZE ,FROMHOUR ,TOHOUR ,DAILYVERSIONS ,MONTHLYVERSIONS
,YEARLYVERSIONS,QUOTAOWNER ,LOCATION ,REQUESTSRETENTION
,CONFIRMATIONTYPE ,SECURITYLEVEL ,DEFAULTACCESSMARKS
,READONLYBYDEFAULT ,USEFILECATEGORIES ,TEXTONLY
,REQUIREREASON ,ENFORCEEXCLUSIVEPASSWORDS
,REQUIRECONTENTVALIDATION ,SHAREOPTIONS ,CONFIRMATIONCOUNT
,MAXFILESIZE ,ALLOWEDFILETYPES,SUPPORTOLAC)






@FOR /F %%i IN (safelist.txt) DO call %PACLI% CLOSESAFE SAFE= %%i


call %PACLI% LOGOFF VAULT="Vault" USER=administrator

call %PACLI% TERM