@echo on

set PACLI="C:\PACLI\PACLI.EXE"
	
call %PACLI% INIT
call %PACLI% DEFINEFROMFILE PARMFILE=Vault.ini
call %PACLI% DEFAULT VAULT="Vault" USER=administrator
call %PACLI% LOGON LOGONFILE=pacli.cred 



FOR /F %%i IN (safelist.txt) DO call %PACLI% OPENSAFE SAFE=%%i





FOR /F %%i IN (safelist.txt) DO call %PACLI% ADDOWNER VAULT="vault" USER=administrator OWNER=PasswordManager SAFE="Development-Web" RETRIEVE=YES STORE=YES DELETE=YES ADMINISTER=NO SUPERVISE=YES BACKUP=NO MANAGEOWNERS=NO ACCESSNOCONFIRMATION=NO VALIDATESAFECONTENT=NO LIST=NO USEPASSWORD=YES UPDATEOBJECTPROPERTIES=YES INITIATECPMCHANGE=YES INITIATECPMCHANGEWITHMANUALPASSWORD=YES CREATEFOLDER=YES DELETEFOLDER=YES MOVEFROM=YES MOVEINTO=YES VIEWAUDIT=YES VIEWPERMISSIONS=YES EVENTSLIST=YES ADDEVENTS=YES CREATEOBJECT=YES UNLOCKOBJECT=NO RENAMEOBJECT=YES

FOR /F %%i IN (safelist.txt) DO call %PACLI% CLOSESAFE SAFE= %%i


call %PACLI% LOGOFF VAULT="Vault" USER=administrator

call %PACLI% TERM